export * from './timetable/Timetable.interface'
export * from './components.interface'
export * from './board/Board.interface'
export * from './hero/Hero.interface'
export * from './solo/Solo.interface'
export * from './testimonial/Testimonial.interface'
export * from './componentKeys'