export * from './home.interface'
export * from './global.interface'
export * from './about.interface'
export * from './articles.interface'
export * from './carte.interface'
export * from './producteur.interface'